name: Semantic Release

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: write

jobs:
  check:
    name: Check Conventional Commits
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Conventional Commits
        uses: webiny/action-conventional-commits@v1.3.0

  release:
    needs: check
    runs-on: ubuntu-latest
    name: Semantic Release
    outputs:
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4.1.1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
